import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footers from "@/components/Footers";
import { PostProvider } from "@/components/Postcontext";
import RightBar from "@/components/RightBar";
import Leftbar from "@/components/Leftbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  <PostProvider>
        <Header/>
        <div className="hidden md:flex md:h-[calc(100vh-22px)] md:w-full">
          <div className="flex-[2] w-full h-full text-center justify-center items-center border border-r-red-400">
            <RightBar />
          </div>
          <div className="flex-[6] text-center border border-r-red-400">
            {children} {/* This replaces Outlet */}
          </div>
         
        </div>
        <div className="md:hidden">
        {children}
        </div>
       
        <Footers/>
        </PostProvider>
      </body>
    </html>
  );
}
